# general
seed: 0 # run seed

# channel
channel_type: 'MIMO' # Channel type values: ['MIMO'].
channel_model: 'Synthetic' # Physical channel models: ['Cost2100','Synthetic']
detector_type: 'black_box'# 'deepsic' or 'black_box' or 'meta_deepsic'
linear: True # channel linearity. Boolean value.
fading_in_channel: True # If the channel is fading/non-fading. values: [True, False]
snr: 12 # validation SNR value. values: float.
modulation_type: 'QPSK' # ['BPSK','QPSK']
n_user: 4 # number of transmitting devices
n_ant: 4 # number of received signals

# protocol
block_length: 50000 # coherence block time, total size of pilot + data. values: int.
pilot_size: 200 # pilot bits
blocks_num: 30 # number of validation frames. values: int.

# online training hyperparameters
is_online_training: True # Whether to run the online training (as in ViterbiNet). values: [True, False].
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.

# augmentations
aug_type: [ ] # ['geometric_augmenter','translation_augmenter','rotation_augmenter']
online_repeats_n: 0  # number of desired augmented words out of online_total_words. values: 0<=online_repeats_n<=online_total_words