# general
seed: 0 # run seed

# channel
channel_type: 'MIMO' # Channel type values: ['MIMO'].
channel_model: 'Synthetic' # Physical channel models: ['Cost2100','Synthetic']K
detector_type: 'online_deepsic'# 'joint_black_box' or 'online_black_box' or 'joint_deepsic' or 'online_deepsic' or 'meta_deepsic'
linear: True # channel linearity. Boolean value.
fading_in_channel: True # If the channel is fading/non-fading. values: [True, False]
snr: 10 # validation SNR value. values: float.
modulation_type: 'QPSK' # ['BPSK','QPSK']
n_user: 4 # number of transmitting devices
n_ant: 4 # number of received signals

# validation phase protocol
block_length: 50400 # coherence block time, total size of pilot + data. values: int.
pilot_size: 400 # pilot bits
blocks_num: 50 # number of validation frames. values: int.

# training hyperparameters
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.

# joint training hyperparameters
joint_block_length: 50000
joint_pilot_size: 1000
joint_blocks_num: 1
joint_snr: 0

# augmentations
aug_type: [ ] # ['geometric_augmenter','translation_augmenter','rotation_augmenter']
online_repeats_n: 0  # number of desired augmented words out of online_total_words. values: 0<=online_repeats_n<=online_total_words